# general
batch_size: 128
input_size: 112
embd_shape: 256
sub_name: 'arc_mbv2_075'
backbone_type: 'MobileNetV2_075' # 'ResNet50', 'MobileNetV2'
head_type: ArcHead # 'ArcHead', 'NormHead'
is_ccrop: False # central-cropping or not

# train
train_dataset: './data/ms1m_bin.tfrecord'
binary_img: True
num_classes: 85742
num_samples: 5822653
epochs: 20
base_lr: 0.01
w_decay: !!float 5e-5
save_steps: 1000

# test
test_dataset: '/your/path/to/test_dataset'
